export enum Title {
  NOOB = 'NOOB',
  PORTE_CHAUSSETTES = 'PORTE_CHAUSSETTES',
  RODEUR_TIMIDE = 'RODEUR_TIMIDE',
  DISCIPLINAIRE_DEBUTANT = 'DISCIPLINAIRE_DEBUTANT',
  SCRIBE_DES_TACHES = 'SCRIBE_DES_TACHES',
  MERCENAIRE_ORGANISE = 'MERCENAIRE_ORGANISE',
  TEMPLIER_DE_L_EFFORT = 'TEMPLIER_DE_L_EFFORT',
  ELU_DES_HABITUDES = 'ELU_DES_HABITUDES',
  PALADIN_DU_QUOTIDIEN = 'PALADIN_DU_QUOTIDIEN',
  ARCHIMAGE_DE_LA_CONSTANCE = 'ARCHIMAGE_DE_LA_CONSTANCE',
}
